openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is documentation of contacts app

tags:
  - name: Contacts
    description: Operations with contacts.

servers:
  - url: https://nodejs-hw-mongodb-7-zvjv.onrender.com
    description: Production server
  - url: http://127.0.0.1:3000
    description: Local development server

paths:
  /contacts/{id}:
    get:
      $ref: '../swagger/paths/contacts/{id}/get.yaml'
    patch:
      $ref: '../swagger/paths/contacts/{Id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{Id}/delete.yaml'
  /contacts:
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
